name: Build package
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.14"
      - name: Clean dist folder
        run: rm -rf dist
      - name: Install dependencies
        run: poetry install
      - name: Build package
        run: poetry build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: dist/
